unit tests for profile service
Third-Floor-CSIS/cs4337-Big-Data-Group pull request #100
Opened 2024-12-02 01:33 UTC by faad555

2024-12-02 16:28 UTC, M-Byte480 requested changes
Could you delete `TemplateProjectApplicationTest.java` and could you do some simple tests for the controller

2024-12-02 23:52 UTC, M-Byte480 approved these changes

2024-12-03 12:05 UTC, Silver-Golden approved these changes
Looks good, although I am curious why the file in the template project is being deleted.

2024-12-03 12:05 UTC, Silver-Golden commented on Microservices/Profile/src/test/java/cs4337/group_8/TemplateProject/ProfileMicroserviceApplicationTests.java
Out of curiousity why is this being deleted? Its not in Profile

2024-12-03 12:05 UTC, Silver-Golden commented on Microservices/Profile/pom.xml
> +
Just be careful of unintended whitespace (not really an issue in the grand run of things)

2024-12-03 12:05 UTC, Silver-Golden commented on Microservices/Profile/src/test/java/cs4337/group_8/ProfileService/controllers/TestProfileController.java
Looks good, (if it was being used a 3rd time I would have recommended that ye make the profile string (L85-L94) to be a constant stored in the class instead of each function)

2024-12-03 20:06 UTC, merged