Adding Basic Files
Third-Floor-CSIS/cs4337-Big-Data-Group pull request #15
Opened 2024-10-15 18:22 UTC by Ben-H0G

Springboot app using JDK 21 and Maven. Named it "instasham" because I found it funny.
The dependencies are in the pom.xml file. Seperate folders for controllers, entities, repositories, and services.

Proposing this structure, maybe we could add a seperate folder for pom.xml files not sure what would be best.

TODO:
Figure out why there's two .gitignore files now...
Replace the dockerfile with something useful

2024-10-15 23:27 UTC, Silver-Golden requested changes
Overall looks like a good foundation.  
The name is fantastic!

I presume that this will be the core program that will use other microservices?

2024-10-15 23:27 UTC, Silver-Golden commented on instasham/instasham/.gitattributes
No, dont do this, leave the ``.gitattributes`` at the top level of the project.

2024-10-15 23:27 UTC, Silver-Golden commented on instasham/instasham/.gitignore
You were wondering why there is a second ``.gitignore`` right?  
Well ye can have as many as ye like and this allows finer grained control over what is ignored.  
This one is specially tailored for springboot whereas the top level one is more general.

2024-10-15 23:27 UTC, Silver-Golden commented on instasham/instasham/Dockerfile
What do ye actually want to do with this?  
Like what is its goal?  

If there is no reason for it now (and if its unlikely to be used in teh near future) then it would be best to remove this.

2024-10-15 23:27 UTC, Silver-Golden commented on instasham/instasham/src/main/resources/application.properties
> +spring.datasource.url = jdbc:mysql://localhost:port/databasename
Is ``port`` a placeholder?  
I know we will eventually replace this with an env var but this should be a number right?

2024-10-15 23:27 UTC, Silver-Golden commented on instasham/instasham/src/main/resources/application.properties
> +server.port=port number
Same for ``port number`` right?

2024-11-08 23:19 UTC, M-Byte480 commented
Abandoning

2024-11-08 23:19 UTC, closed without merging