Api gateway services
Third-Floor-CSIS/cs4337-Big-Data-Group pull request #37
Opened 2024-10-26 12:42 UTC by faad555

created three Api-services 
I followed MVC structure. each have it's controller where we can add deferent actions later example ../profile/view, ../profile/create etc
and each service have its own model that have its methods.

2024-10-26 18:03 UTC, Silver-Golden requested changes
Overall grand, however there are two main things

1. You are using eclipse but didnt update teh ``.gitignore`` to reflect this, as such a mountain of (local) config files and compiled binaries got added
    ```gitgnore
    .classpath
    .project
    /.settings
    /**/.settings
    /target
    /**/target
    ```
2. The microservices are in teh wrong locaiton, they should be inside the ``Microservices`` folder

Fix those issues then come back for a review of the code without it being cluttered up by all the excess files

2024-10-27 23:10 UTC, M-Byte480 commented
I am little confused on what the proposed code provides?

There is not routing or distribution logic it appears. Quick google search gave me this article: https://medium.com/@ankithahjpgowda/api-gateway-in-spring-boot-3ea804003021 

Which has a well written explanation of what should be achieved. If you need more context please let me know. 

I'd propose to have some skeleton ready to go and we can connect them up later

2024-10-27 23:21 UTC, M-Byte480 requested changes

2024-10-27 23:21 UTC, M-Byte480 commented on api-services/auth-service/pom.xml
> +    <!-- lookup parent from repository -->
Remove these comments please

2024-10-27 23:21 UTC, M-Byte480 commented on api-services/post-service/pom.xml
> +		<!-- lookup parent from repository -->
Same here

2024-10-27 23:32 UTC, M-Byte480 commented
I wish the project had a bit more structure as in the microservices:
![image](https://github.com/user-attachments/assets/357071fe-bd9d-45ae-9a35-ac6a00c2b51f)
I am confused on the duplication, and also the apps in the upper half dont seem to read the properties. Is this meant to be a guideline? 

Also I am struggling to see where the redirects would occur. Can you post a screenshot or two on what is supposed to happen?
For me even though you have 8081 specified, it is not read:
![image](https://github.com/user-attachments/assets/eb4018bf-bbd3-43a0-9e2d-4450dfafed71)


This is a note for me (and potentially you):
https://medium.com/@ankithahjpgowda/api-gateway-in-spring-boot-3ea804003021

2024-10-28 17:12 UTC, M-Byte480 commented
I feel like there is a bit of confusion what the API-Gateway is supposed to be doing. 

It takes in the request and maps it to the correct Microservice. It is supposed to be an independent API, not a collection of 3 (which is not your responsibility).

2024-11-08 21:57 UTC, M-Byte480 commented
Closed as it is no longer used

2024-11-08 21:57 UTC, closed without merging