feat: Oauth 2.0 with Google
Third-Floor-CSIS/cs4337-Big-Data-Group pull request #40
Opened 2024-10-27 23:52 UTC by M-Byte480

There is a `./frontend` in the root:
![image](https://github.com/user-attachments/assets/8f95b09d-c219-49a0-bfc3-bb5c0e921a2d)

This is just a hyperlink to Google Oauth for our application:
![image](https://github.com/user-attachments/assets/e5f7a613-55a1-4892-bad1-eca09f10e27e)

THIS WILL NOT WORK FOR YOU UNLESS I ADD YOU AS A TEST USER TO GOOGLE SYSTEM:
![image](https://github.com/user-attachments/assets/cb27f131-5dfc-4127-8a38-efa1d7997b90)
Upon successful authentication we get the pair of Access and Refresh token. We note the expirations in the DB and at the moment there is a get request with the user details:
![image](https://github.com/user-attachments/assets/d0647e1f-7f5c-49fc-a9c4-d295bcca3f0d)
If the user does not exists, we note them in the DB as a new user.

There are two secrets that I need to share with you to run the application: Client_id and client_secret

Will write more unit tests for the Google Authentication Service, as much as I disagree with testing APIs, the coverage is only at 50% with not testing it -_-

2024-11-04 14:37 UTC, silpac-12 approved these changes

2024-11-08 22:07 UTC, Silver-Golden requested changes
Looks good, except for teh moving of files.

You may also want to do this to fetch the latest changes from main.

```bash
git fetch origin main
git rebase origin/main
```

2024-11-08 22:07 UTC, Silver-Golden commented on Microservices/TemplateProject/src/main/java/cs4337/group_8/AuthenticationMicroservice/DTO/SampleDTO.java
I think ye may have messed up something here considering that this is being moved not copied.

2024-11-08 22:07 UTC, Silver-Golden commented on frontend/index.html
Looks good

2024-11-08 22:30 UTC, M-Byte480 commented on frontend/index.html
thanks

2024-11-08 22:30 UTC, M-Byte480 commented on Microservices/TemplateProject/src/main/java/cs4337/group_8/AuthenticationMicroservice/DTO/SampleDTO.java
I believe this file no longer exists.

2024-11-08 23:07 UTC, Silver-Golden approved these changes
Looks good to me!

2024-11-08 23:08 UTC, merged