api gateway and service registry added
Third-Floor-CSIS/cs4337-Big-Data-Group pull request #49
Opened 2024-11-01 17:06 UTC by faad555

The service registry will keep the record of all the services e.g auth service, post service, profile service etc
Api-gateway communicate with services via service registry.
So any request comes in to the Api-gateway, the API-gateway checks with Service registry if the service is available and On. Then it will hit the related microservice. so if there's no service registered in the "Service registry" the API-gateway wont be able to communicate with microservice.

2024-11-01 22:28 UTC, M-Byte480 requested changes

2024-11-01 22:28 UTC, M-Byte480 commented on Microservices/api-gateway/pom.xml
> +	<groupId>com.fawad</groupId>
Change this to cs4337.group-8

2024-11-01 22:28 UTC, M-Byte480 commented on Microservices/api-gateway/pom.xml
> +		<groupId>org.springframework.boot</groupId>
The parent should inherit from our parent:
    <parent>
        <groupId>cs4337.group-8</groupId>
        <artifactId>parent-microservices</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

2024-11-03 00:54 UTC, Silver-Golden commented
How does this relate to #37 ?  
Should both PR's be open?

2024-11-05 15:30 UTC, M-Byte480 approved these changes

2024-11-08 21:59 UTC, Silver-Golden approved these changes
Assuming #37 is no longer required this can be merged in

2024-11-08 23:01 UTC, merged