Brendan/#34 profile foundations
Third-Floor-CSIS/cs4337-Big-Data-Group pull request #51
Opened 2024-11-03 00:52 UTC by Silver-Golden

Not 100% sure that this is correct, I have a rough idea how it all *should* work but not about the specifics.  
Core function behind this is getting and setting profile data.  
Last time I checked I was able to build it, but running it was failing on accessing teh database.  
I will create a new issue to get a database config up and running, at least on a temp basis

2024-11-03 17:35 UTC, M-Byte480 requested changes
Just a couple of nit picks
TODO: add unit tests

2024-11-03 17:35 UTC, M-Byte480 commented on Microservices/Profile/src/main/java/cs4337/group_8/TemplateProject/DTO/ProfileDTO.java
> +//    public ProfileDTO (String property1){
Can you remove this

2024-11-03 17:35 UTC, M-Byte480 commented on Microservices/Profile/src/main/java/cs4337/group_8/TemplateProject/controllers/ProfileController2.java
Can you rename it without the 2

2024-11-03 17:35 UTC, M-Byte480 commented on Microservices/Profile/src/main/java/cs4337/group_8/TemplateProject/controllers/ProfileController2.java
On that note, can you change the package name to profileMicroservice or similar (profilems)

2024-11-03 17:35 UTC, M-Byte480 commented on Microservices/Profile/src/main/java/cs4337/group_8/TemplateProject/repositories/ProfileRepository.java
> +    // Where ?1 is the first parameter of the method
Can you remove all the comments

2024-11-03 17:35 UTC, M-Byte480 commented on Microservices/Profile/src/main/java/cs4337/group_8/TemplateProject/services/ProfileService.java
>              }
Commented code here

2024-11-03 23:40 UTC, M-Byte480 requested changes

2024-11-03 23:40 UTC, M-Byte480 commented on Microservices/Profile/src/main/java/cs4337/group_8/TemplateProject/DTO/ProfileDTO.java
> +//    }
Remove the commented out code

2024-11-03 23:40 UTC, M-Byte480 commented on Microservices/Profile/src/main/java/cs4337/group_8/TemplateProject/entities/ProfileEntity.java
> +//    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-increment in the database
Commented out generationPattern

2024-11-03 23:40 UTC, M-Byte480 commented on Microservices/Profile/src/main/java/cs4337/group_8/TemplateProject/repositories/ProfileRepository.java
> +    //Optional<List<ProfileEntity>> findAllByFirstnameAndVerified(String firstname, boolean verified);
Unused queries

2024-11-03 23:40 UTC, M-Byte480 commented on Microservices/Profile/src/main/java/cs4337/group_8/TemplateProject/controllers/ProfileController2.java
Can you remove the 2 and also rename the package from TemplateProject

2024-11-03 23:40 UTC, M-Byte480 commented on Microservices/Profile/src/main/java/cs4337/group_8/TemplateProject/services/ProfileService.java
> +                return new ArrayList<ProfileEntity>();
Commented code

2024-11-04 09:05 UTC, Silver-Golden commented on Microservices/Profile/src/main/java/cs4337/group_8/TemplateProject/controllers/ProfileController2.java
Funnily enough it failed to compile without it, kept claiming there was a conflict, even when I cleared the build cache, might end up naming it to be something else.

2024-11-10 21:11 UTC, M-Byte480 approved these changes
Good enough for starters

2024-11-12 17:14 UTC, Bourkupine reviewed
Left comments

2024-11-12 17:14 UTC, Bourkupine commented on Microservices/Profile/pom.xml
> +	<artifactId>TemplateProject</artifactId>
Should this not be 'Profile'

2024-11-12 17:14 UTC, Bourkupine commented on Microservices/Profile/pom.xml
> +	<name>TemplateProject</name>
same as above

2024-11-13 17:41 UTC, M-Byte480 commented
@Bourkupine @faad555 @killianC2323 @silpac-12 Can you guys take a look, I registered the application onto Eureka

2024-11-14 16:40 UTC, Silver-Golden commented on Microservices/service-registry/src/main/resources/application.properties
Seems @M-Byte480 removed it in 0a6cb6a3250e18c2d212825accdbe1d89012f5e0

2024-11-14 17:05 UTC, M-Byte480 commented on Microservices/service-registry/src/main/resources/application.properties
Ye Service Registry is not a standalone api so it cant actually create and read DB. That is why each microservice will have their own db to read and write from

2024-11-15 16:13 UTC, M-Byte480 approved these changes

2024-11-15 16:28 UTC, Bourkupine approved these changes
Looks good to me, good work Brendan.

2024-11-20 21:36 UTC, merged