New branch on main
Third-Floor-CSIS/cs4337-Big-Data-Group pull request #58
Opened 2024-11-12 11:04 UTC by silpac-12

2024-11-12 17:59 UTC, Bourkupine reviewed
Left some comments, some are nitpicks but dont hate me

2024-11-12 18:15 UTC, silpac-12 commented on .env.example
> +MYSQLDB_PORT=3307
my bad changed it on my machine because 3306 was being used, slipped my mind to change back

2024-11-12 19:03 UTC, silpac-12 commented on Microservices/Posts/src/main/resources/application.properties
> +DB_PORT=3307
As in similar to how it is done further down in the file like this? ${MYSQL_USERNAME}

2024-11-12 22:06 UTC, Bourkupine commented on Microservices/Posts/src/main/resources/application.properties
> +DB_PORT=3307
kinda you'll need to import variables from the .env file;
1. add a .env file (see the #resources channel in the discord)
2. change this file to mimic that of the application.properties in template project (Microservices/TemplateProject/src/main/resources/application.properties)
making sure to add the import at the top of the file

If you need any more help feel free to respond here or @ me in discord

2024-11-12 22:10 UTC, Bourkupine reviewed
Just a small nitpick regarding the pom file

2024-11-12 22:10 UTC, Bourkupine commented on Microservices/Posts/pom.xml
> +	<name>TemplateProject</name>
Sorry to unresolve this. You can keep artifactId as Posts, just update <name>TemplateProject<name> to PostsMicroservice or something similar

2024-11-13 10:46 UTC, silpac-12 commented on Microservices/Posts/src/main/resources/application.properties
> +DB_PORT=3307
think ive got it, let me know if anything else needs to change

2024-11-13 17:05 UTC, M-Byte480 commented
What exactly is the purpose of this PR?

2024-11-14 10:29 UTC, silpac-12 commented
> What exactly is the purpose of this PR? 

Just adds my Post microservice to main, had to make a new pr and deleted the old one because I messed up rebasing the first one

2024-11-14 10:45 UTC, M-Byte480 approved these changes

2024-11-14 15:03 UTC, Bourkupine approved these changes
Will approve however I'm a little unsure on whether the log files should be included

2024-11-14 15:04 UTC, Silver-Golden requested changes
Log files should not be included

2024-11-14 15:04 UTC, Silver-Golden commented on Microservices/Posts/logs/app.log
Log files should not be included

2024-11-14 16:11 UTC, Silver-Golden commented on Microservices/Posts/logs/app.log
Add these to teh giginore to ensure they arent committed again

```gitignore
.log
.log.*
```

2024-11-14 16:17 UTC, Bourkupine approved these changes
Looks good, great job, best iv seen. Approved

2024-11-14 16:24 UTC, Silver-Golden commented on Microservices/Posts/logs/app.log
Would much prefer if ye had added it to teh root .gitignore since it will cover all future cases

2024-11-14 16:25 UTC, silpac-12 commented on Microservices/Posts/logs/app.log
No problem

2024-11-14 16:26 UTC, Bourkupine commented
Looks like I need to revoke my comment regarding the great job, best iv seen

2024-11-14 20:49 UTC, Silver-Golden approved these changes
Looks good!

2024-11-15 13:10 UTC, merged