Docker for Posts
Third-Floor-CSIS/cs4337-Big-Data-Group pull request #85
Opened 2024-11-23 18:49 UTC by silpac-12

2024-11-23 18:54 UTC, M-Byte480 requested changes
Do you want to add it to docker-compose.yml so we can nicely build it from there? Look at profile or auth's PR on how to do it

2024-11-23 18:57 UTC, silpac-12 commented
> Do you want to add it to docker-compose.yml so we can nicely build it from there? Look at profile or auth's PR on how to do it

Yea I see what you mean, nb

2024-11-24 17:45 UTC, Silver-Golden approved these changes
Looks good to me

2024-11-28 15:54 UTC, M-Byte480 approved these changes

2024-11-28 16:57 UTC, merged