Added unit test pipeline
Third-Floor-CSIS/cs4337-Big-Data-Group pull request #9
Opened 2024-10-08 17:11 UTC by M-Byte480

Added unit test pipeline

2024-10-08 17:21 UTC, Silver-Golden requested changes

2024-10-08 17:21 UTC, Silver-Golden commented on .github/workflow/main.yml
> +name: CI
THis is a bad name, what is this workflow for?

2024-10-08 17:21 UTC, Silver-Golden commented on .github/workflow/unit_test.yml
> +name: Java CI with Maven
This should be something like "Build"

2024-10-08 19:00 UTC, Bourkupine requested changes

2024-10-08 19:00 UTC, Bourkupine commented on .github/workflow/unit_test.yml
> +      - name: Set up JDK 17
17 should be 21

2024-10-09 12:52 UTC, Bourkupine approved these changes
Looks good, is there a specific reason for using Temurin?

2024-10-09 22:47 UTC, Silver-Golden requested changes
30 line PR === extensive comments  
3000 line PR === sure it looks grand

2024-10-09 22:47 UTC, Silver-Golden commented on .github/workflow/main.yml
Honestly why is this file here?  
As far as I can tell it does nothing.  

Each file is its own workflow, you dont have to have a file to declare what other workflows exist.  
Ye cna take a look at https://forgejo.skynet.ie/Skynet/nixos/src/branch/main/.forgejo/workflows for an example of this, 3 workflows.  
You can see on the left of this page https://forgejo.skynet.ie/Skynet/nixos/actions the workflows, select each one to see the runs for that particular one.

2024-10-09 22:47 UTC, Silver-Golden commented on .github/workflow/unit_test.yml
> +name: Build
This is not a build workflow, its a unit test one, update name to reflect that (or remove this line

2024-10-09 22:47 UTC, Silver-Golden commented on .github/workflow/unit_test.yml
> +
In the other file you have ``workflow_dispatch:``.  
This is useful to have here to allow us to manually run the workflow.

2024-10-09 22:47 UTC, Silver-Golden commented on .github/workflow/unit_test.yml
> +
Ye can remove this line to help group the workflow together visually

2024-10-09 22:47 UTC, Silver-Golden commented on .github/workflow/unit_test.yml
> +
Same with just above, remove this line for visual reasons

2024-10-09 22:47 UTC, Silver-Golden commented on .github/workflow/unit_test.yml
> +      - name: Build with Maven
This is to run the unit test right? so ``Run unit tests using Maven`` would be more apt

2024-10-11 13:44 UTC, M-Byte480 commented
I'll fix these tonight

2024-10-12 21:08 UTC, Silver-Golden approved these changes
Looks good!

2024-10-13 21:46 UTC, Bourkupine approved these changes
Looks good, make sure to squash commits

2024-10-13 21:46 UTC, merged