changelog now sql file
Third-Floor-CSIS/cs4337-Big-Data-Group pull request #99
Opened 2024-12-01 14:46 UTC by silpac-12

2024-12-02 16:29 UTC, M-Byte480 requested changes

2024-12-02 16:29 UTC, M-Byte480 commented on Microservices/Posts/src/main/resources/db/db.changelog-master.sql
> +        CREATE TABLE posts (
Could you add
`CREATE TABLE IF NOT EXISTS ` to the two tables

2024-12-02 16:38 UTC, killianC2323 approved these changes
looks good

2024-12-03 11:52 UTC, Silver-Golden approved these changes
Looks good to me.  
(definitely in favor of sql over xml for this)

2024-12-03 12:56 UTC, merged